### ISSUE TITLE
Tagpack export in the dashboard requires updates to adhere to the new tagpack design.

### ISSUE THREAD

**Issue by mdragaschnig** [iknaio/graphsense-dashboard#35]
Currently, annotating entities

![01](https://user-images.githubusercontent.com/47592782/158128569-d90eeae2-e01a-4ff7-bb3b-5009df72a2ae.png)

and exporting the annotations produces this tagpack yaml:

<pre><code>
title: Tagpack exported from GraphSense 0.5.1
creator: tester
tagpack_uri: null
currency: ETH
tags:
    <b>- label: entitytag
    source: http://m.brain.org
    lastmod: 2022-03-14 07:24:09
    category: item
    abuse: null
    entity: 19905716</b>
  - label: addresstag
    source: http://brain.org
    lastmod: 2022-03-14 07:43:26
    category: null
    abuse: service_hack
    address: "0x5e575279bf9f4acf0a130c186861454247394c06"
</pre></code>

which is no longer valid.

The most important issue is that the concept of entity tags in tagpacks no longer exist.

It should therefore not be possible to export entity tags.

Further updates required:
* Field `tagpack_uri` is obsolete.
* Values of header field `entity` resp. `abuse` must not be null. If no value is given by the user, the fields must not appear in the exported tagpack file.

**Comment by mdragaschnig** [comment]
That should take care of the main issue, thanks!

Only small fixes remain now:
*  Field `tagpack_uri` is obsolete.
*  If no value is given by the user for `entity` resp. `abuse`, the fields must not appear in the exported tagpack file.

**Comment by myrho** [comment]
Ok, sorry, is also fixed now

**Comment by mdragaschnig** [comment]
It seems clusters cannot be tagged:

What I did:

Log in.

Open address 1NAeNVgw9ZRvDyzCxJAAo5dAaPyoygckQZ

Tag the cluster:

![after](https://user-images.githubusercontent.com/47592782/159499049-61716762-b729-4e7b-aee3-662a07b6c78c.png)

Save the tagpack.

The cluster address is missing:

<pre>
title: Tagpack exported from GraphSense 0.5.2-dev
creator: me
label: clusterlabel
source: source
currency: BTC
lastmod: 2022-03-22 14:00:03
category: market
is_cluster_definer: true
tags:
  <b>- ? address</b>
</pre>

**Comment by mdragaschnig** [comment]
It's not deployed on test.graphsense.info.

But if you cannot reproduce it locally then the problem ought to be elsewhere.

Thank you for checking!
